services:
  analytics:
    build: .
    environment:
      MAIN_PRODUCTION: 'true'
      MAIN_SECRETKEY: ${SECRET_KEY:-Incremental Game}
      MAIN_EXPIRY: ${TOKEN_EXPIRY:-3600}
    ports:
      - ${SERVER_BIND:-127.0.0.1:8000}:8000
    volumes:
      - ./analytics_data:/app/data
